export const calcButtonData = [
  {
    title: "AC",
    id: "0",
    backgroundColor: "#a6a6a6",
    noMargin: false,
  },
  {
    title: "±",
    id: "1",
    backgroundColor: "#a6a6a6",
    noMargin: false,
  },
  {
    title: "%",
    id: "2",
    backgroundColor: "#a6a6a6",
    noMargin: false,
  },
  {
    title: "÷",
    id: "3",
    backgroundColor: "#f09a36",
    noMargin: true,
  },
  {
    title: "mc",
    id: "4",
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "mr",
    id: "5",
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "m-",
    id: "6",
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "m+",
    id: "7",
    backgroundColor: "#f09a36",
    noMargin: true,
  },
  {
    title: "7",
    id: "8",
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "8",
    id: "9",
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "9",
    id: "10",
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "×",
    id: "11",
    backgroundColor: "#f09a36",
    noMargin: true,
  },
  {
    title: "4",
    id: "12",
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "5",
    id: "13",
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "6",
    id: "14",
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "-",
    id: "15",
    backgroundColor: "#f09a36",
    noMargin: true,
  },
  {
    title: "1",
    id: "16",
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "2",
    id: "17",
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "3",
    id: "18",
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "+",
    id: "19",
    backgroundColor: "#f09a36",
    noMargin: true,
  },
  {
    title: "0",
    id: "20",
    backgroundColor: "#333333",
    largeButtom: true,
  },
  {
    title: ".",
    id: "21",
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "=",
    id: "22",
    backgroundColor: "#f09a36",
    noMargin: true,
  },
];
