export const calcButtonData = [
  {
    title: "AC",
    id: "0",
    type: "clear",
    backgroundColor: "#a6a6a6",
    noMargin: false,
  },
  {
    title: "±",
    id: "1",
    type: "plus-minus",
    backgroundColor: "#a6a6a6",
    noMargin: false,
  },
  {
    title: "%",
    id: "2",
    type: "percentage",
    backgroundColor: "#a6a6a6",
    noMargin: false,
  },
  {
    title: "÷",
    id: "3",
    type: "operator",
    value: "/",
    backgroundColor: "#f09a36",
    noMargin: true,
  },
  {
    title: "mc",
    type: "mc",
    id: "4",
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "mr",
    id: "5",
    type: "mr",
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "m-",
    id: "6",
    type: "m-",
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "m+",
    id: "7",
    type: "m+",
    backgroundColor: "#f09a36",
    noMargin: true,
  },
  {
    title: "7",
    id: "8",
    type: "number",
    value: 7,
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "8",
    id: "9",
    type: "number",
    value: 8,
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "9",
    id: "10",
    type: "number",
    value: 9,
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "×",
    id: "11",
    type: "operator",
    value: "*",
    backgroundColor: "#f09a36",
    noMargin: true,
  },
  {
    title: "4",
    id: "12",
    type: "number",
    value: 4,
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "5",
    id: "13",
    type: "number",
    value: 5,
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "6",
    id: "14",
    type: "number",
    value: 6,
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "-",
    id: "15",
    type: "operator",
    value: "-",
    backgroundColor: "#f09a36",
    noMargin: true,
  },
  {
    title: "1",
    id: "16",
    type: "number",
    value: 1,
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "2",
    id: "17",
    type: "number",
    value: 2,
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "3",
    id: "18",
    type: "number",
    value: 3,
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "+",
    id: "19",
    type: "operator",
    value: "+",
    backgroundColor: "#f09a36",
    noMargin: true,
  },
  {
    title: "0",
    id: "20",
    type: "number",
    value: 0,
    backgroundColor: "#333333",
    largeButtom: true,
  },
  {
    title: ".",
    id: "21",
    type: "number",
    value: ".",
    backgroundColor: "#333333",
    noMargin: false,
  },
  {
    title: "=",
    id: "22",
    type: "equal",
    backgroundColor: "#f09a36",
    noMargin: true,
  },
];
